name: QA

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        
    - name: Compute branch name
      uses: nelonoel/branch-name@v1.0.1

    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v8

      # Анализ проекта в SonarQube (ветка)
    - name: Анализ в SonarQube (branch)
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: sonar-scanner
        -Dsonar.host.url=https://sonar.openbsl.ru
        -Dsonar.branch.name=${{ env.BRANCH_NAME }}
   
